### ISSUE TITLE
load yolo custom model

### ISSUE THREAD

**Issue by kozka** [zqingr/tfjs-yolov3#5]
Hello
I created a model.weights from yolov3
I wonder if it is possible to load it to work ?

thank you

**Comment by zqingr** [comment]
Sorry, I haven't finished the logic of custom model. You can see this [project](https://github.com/qqwweee/keras-yolo3). I refer to this project.

**Comment by zhubinsheng** [comment]
> Hello
> I created a model.weights from yolov3
> I wonder if it is possible to load it to work ?
> 
> thank you

hello how to transform weights and work? can you help me thank you for your anwser
