### ISSUE TITLE
请问，怎么启动，给给教程可以吗？

### ISSUE THREAD

**Issue by 12343954** [zqingr/tfjs-yolov3#6]
yarn start 启动之后，报错

![image](https://user-images.githubusercontent.com/1804003/65681977-9583d900-e08c-11e9-8bc5-997619014f71.png)

![image](https://user-images.githubusercontent.com/1804003/65681952-89981700-e08c-11e9-8ca7-be28d188472d.png)

还有，能再给个打包的命令吗？npm run build，yarn build 都打不上包

能写个react.js版本吗？实在搞不定webpack和这些依赖，老是报错

**Comment by zqingr** [comment]
这个项目不是直接启动的。
react只是框架，都可以引入这个js的。
用法参考如下：

[https://github.com/zqingr/tfjs-yolov3#%E7%94%A8%E6%B3%95%E7%A4%BA%E4%BE%8B](https://github.com/zqingr/tfjs-yolov3#%E7%94%A8%E6%B3%95%E7%A4%BA%E4%BE%8B)
