### ISSUE TITLE
请问我的anchor参数，和labels是如下的，其中anchor是二维数组的这种，不是一维的，要怎么用您的这个项目

### ISSUE THREAD

**Issue by MRchenao** [zqingr/tfjs-yolov3#7]
"labels" : [
        "hololens"
    ],
    "anchors" : [
        [160, 171, 261, 167, 301, 285],
            [78, 86, 104, 69, 138, 105],
            [37, 32, 58, 61, 62, 44]
    ]

**Comment by zqingr** [comment]
如果要改成这种anchors的话或需要改源码哦，很可惜我也不知道怎么改
看你的labels里面的hololens，这个项目的model是不支持的，你需要训练自己的model后识别hololens

**Comment by MRchenao** [comment]
> 如果要改成这种anchors的话或需要改源码哦，很可惜我也不知道怎么改
> 看你的labels里面的hololens，这个项目的model是不支持的，你需要训练自己的model后识别hololens

是的，我用的是自己自定义训练的模型，也是用的yolov3的模型训练的。但是我训练出来的anchors不是一维的，我用的是imageAI的这个来训练的，直接拿他的demo来生成json模型文件https://github.com/OlafenwaMoses/ImageAI/blob/master/imageai/Detection/Custom/CUSTOMDETECTIONTRAINING.md那我再研究研究，看看怎么修改，如果您看后有什么修改想法的话，也请告知。嘻嘻

**Comment by zqingr** [comment]
好的，另外你可以参考下这个[项目](https://github.com/qqwweee/keras-yolo3)，我这个项目就是参考的这个
