### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by zhubinsheng** [zqingr/tfjs-yolov3#9]
Document.html:341 Uncaught (in promise) TypeError: yolov3Tiny is not a function
    at start (Document.html:341)
    at Document.html:350

i had this question,i use it in electron
i only use your index.bundle.js to run ok
我无法使用如下的方式去运行：
用法示例
import { yolov3, yolov3Tiny } from 'tfjs-yolov3'

async function start () {
  const yolo = await yolov3Tiny() // pre-load model (35M)
  // or
  // const yolo = await yolov3() // pre-load model (245M)

  const $img = document.getElementById('img')
  const boxes = await yolo($img) 
  draw(boxes) // Some draw function
}
start()

**Comment by zqingr** [comment]
tfjs-yolov3 这个库install进去了吗，看起来是tfjs-yolov3这个库引入不正确报的错

**Comment by zhubinsheng** [comment]
> tfjs-yolov3 这个库install进去了吗，看起来是tfjs-yolov3这个库引入不正确报的错

很高兴看到你这么快的回复，tfjs-yolov3 这个库肯定是install进去的了，我在node_modules中也发现了他，但是如果我在./node_modules/tfjs-yolov3中搜索yolov3Tiny是搜索不到的
但是在你的演示项目中的 index.bundle.js文件中是可以搜索到yolov3Tiny，这很奇怪
另外您在这条回复中https://github.com/zqingr/tfjs-yolov3/issues/5#issuecomment-548311327  ，这个库我也用到了，
我将cfg和weights文件用keras-yolo3转化成h5文件，than use tensorflow.js (pip install ) 
tensorflowjs_converter --input_format=keras  --output_format=tfjs_graph_model ./yolo.h5 ./tfjs_model
get model.json and many bin file

**Comment by zhubinsheng** [comment]
我将cfg和weights文件用keras-yolo3这个库转化成h5文件，再用 tensorflow.js (pip install的 )转化成tf.js可以使用的模型文件，命令如下：
tensorflowjs_converter --input_format=keras --output_format=tfjs_graph_model ./yolo.h5 ./tfjs_model
我获得了model.json 和**分层的 bin文件**，但这和你提供的https://github.com/zqingr/tfjs-yolov3/releases/tag/v1.0 release模型文件不同 而且我加载会报错

**Comment by zhubinsheng** [comment]
提前感谢你的耐心 谢谢您

**Comment by zhubinsheng** [comment]
我使用了https://github.com/qqwweee/keras-yolo3 官方说明的环境版本和你的keras版本也一直，
然后使用tensorflowjs                 2.7.0这个版本来转化成tsjs-yolov3.js所需要的model.jso文件，这个版本号你可以提供下吗？
或者你是使用python api来转化的吗

**Comment by zqingr** [comment]
如果跑不起来的话，试试这个项目，https://github.com/zqingr/tfjs-yolov3-demo
这个就是demo项目的源码，两年前的项目了，可能一些依赖升级了，你可以锁定以下package.json里的版本运行下试试

至于怎么转换的话，我记得应该是用的tensorflowjs官方给的转换方法，命令行转换的，应该就是上面的tensorflowjs_converter

**Comment by zhubinsheng** [comment]
感谢，我将继续尝试tensorflowjs版本以生成和你相同的模型文件

**Comment by zhubinsheng** [comment]
I transformed successfully from following，thank for your help
Package              Version
-------------------- ---------
absl-py              0.10.0
astor                0.8.1
bleach               1.5.0
gast                 0.4.0
google-pasta         0.2.0
grpcio               1.33.1
h5py                 2.7.1
html5lib             0.9999999
importlib-metadata   2.0.0
Keras                2.1.4
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.2
Markdown             3.3.3
numpy                1.14.1
pip                  20.2.4
protobuf             3.13.0
PyYAML               5.3.1
scipy                1.5.3
setuptools           50.3.2
six                  1.11.0
tensorboard          1.7.0
tensorflow           1.7.0
tensorflow-estimator 1.14.0
tensorflow-hub       0.1.0
tensorflowjs         0.3.0
termcolor            1.1.0
Werkzeug             1.0.1
wheel                0.35.1
wrapt                1.12.1
zipp                 3.4.0

**Comment by zqingr** [comment]
ok 谢谢提供

**Comment by zhubinsheng** [comment]
然后你的库的特点如下：
可以识别任意尺寸的图片
同时支持yolov3和yolov3-tiny
所以暂不支持像video一样的标签的识别是吗？
此库https://github.com/shaqian/tfjs-yolo 支持如下Supported input html element:
img
canvas
video
我将试试他的库来实时识别物品，谢谢
